[pytest]
# Tells pytest to look one folder up (at the intern-playground root) for the code
pythonpath = ..

# Tells pytest to only run tests found in this specific folder
testpaths = tests

# Default flags for clean, verbose output
addopts = -v